nosana:
  description: Nosana-Node Pipeline

global:
  image: registry.hub.docker.com/library/node:lts

  trigger:
    branch:
      - all

jobs:
  - name: First Job
    commands:
      - npm ci
      - npm run generate
      - npm run ipfs
